version: "3.8"

networks:
  github-actions:
    external: false

volumes:
  runner-data:
    driver: local
    driver_opts:
      type: none
      device: $PWD/runner
      o: bind

services:
  github-runner:
    container_name: github-runner
    restart: always
    env_file:
      - .env
    build:
      context: $PWD/docker/github-runner
      dockerfile: Dockerfile
      args:
        UBUNTU_VERSION: ${UBUNTU_VERSION}
    volumes:
      - runner-data:/home/runner
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - github-actions
